# Generated by Django 5.2.17 on 2026-08-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aerolínea", models.CharField(max_length=50)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField()),
                ("origen", models.CharField(max_length=50)),
                ("destino", models.CharField(max_length=50)),
                ("capacidad", models.PositiveSmallIntegerField()),
                ("disponibilidad", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
