# Generated by Django 5.2.17 on 2026-08-24 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vuelos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentaVuelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_pasajero", models.CharField(max_length=50)),
                ("email_pasajero", models.EmailField(max_length=254)),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                (
                    "vuelo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vuelos.vuelo"
                    ),
                ),
            ],
        ),
    ]
